services:
  - type: web
    name: yumzy-backend
    env: node
    plan: free
    root: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: JWT_SECRET
        value: my_super_secret_key_123
      - key: MONGO_URI
        value: mongodb+srv://sujaldarekar06_db_user:kO5buK1CdSSRgLN1@cluster0.fvlzev8.mongodb.net/food-view?retryWrites=true&w=majority
      - key: IMAGEKIT_PUBLIC_KEY
        value: public_YnUB8H/tpJr5eK8qzVpNeUiUk7k=
      - key: IMAGEKIT_PRIVATE_KEY
        value: private_EKen82MQIOvq+slj4sglarVMXEU=
      - key: IMAGEKIT_URL_ENDPOINT
        value: https://ik.imagekit.io/sujald
  - type: static
    name: yumzy-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    publishDir: frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /index.html
        headers:
          - key: Cache-Control
            value: "no-cache"
    envVars:
      - key: VITE_API_URL
        value: https://yumzy-backend-i24j.onrender.com
