services:
  - type: web
    name: yumzy-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: my_super_secret_key_123
      - key: MONGO_URI
        value: mongodb+srv://sujaldarekar06_db_user:kO5buK1CdSSRgLN1@cluster0.fvlzev8.mongodb.net/food-view?retryWrites=true&w=majority
      - key: IMAGEKIT_PUBLIC_KEY
        value: public_YnUB8H/tpJr5eK8qzVpNeUiUk7k=
      - key: IMAGEKIT_PRIVATE_KEY
        value: private_EKen82MQIOvq+slj4sglarVMXEU=
      - key: IMAGEKIT_URL_ENDPOINT
        value: https://ik.imagekit.io/sujald
    fromComponents:
      - backend
  - type: static
    name: yumzy-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    publishDir: frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: yumzy-backend
          envVar: url
